- go/bin/compare/compare.go
- go/bin/coresvnet/coresvnet.go
- go/bin/score/score.go
- go/data/study.go
- go/progress/bar.go
- Changed default frequency resolution from 8 to 5, which seems to perform better in general.
- Made Study.Put add all a slice of references in the same transaction, which improves performance a lot when using remote drives.
- Made  print all references in the dataset in a single JSON array instead of individual JSON dictionaries to simplify ingestion via JSON.
- Made progress bar use regular average instead of EMA the first 10 seconds.
- Made progress bar use fractional speed instead of completed-units-speed when predicting ETA, since that automatically takes changing number of pending tasks into account.
- Made progress bar able to finish with an actual time of completion.
> Minor improvements.

- cpp/zimt/ux.cc
Crosshair was misaligned when the spectrogram types have very different DTWs since the mapping used the wrong spectrogram type.
> Fixed crosshair bug in UX.

- .github/workflows/test.yml
- go/bin/score/score.go
- go/data/study.go
Example output when analyzing the https://github.com/pranaymanocha/PerceptualAudio/blob/master/dataset/README.md dataset:
```
*** Evaluations with audible distortions and Zimtohrli distance greater than X
5.00   79    (0.03)  #                                             
10.00  103   (0.04)  #                                             
20.00  223   (0.08)  ####                                          
40.00  1226  (0.45)  ######################                        
80.00  2465  (0.90)  ############################################  
*** Evaluations with non-audible distortions and Zimtohrli distance less than X
5.00   1871  (0.64)  ################################  
10.00  1697  (0.58)  #############################     
20.00  1373  (0.47)  #######################           
40.00 …
```
> Added histogram analysis of JND datasets.

- README.md
- cpp/zimt/resample.h
- cpp/zimt/zimtohrli.cc
- go/aio/aio.go
- go/bin/compare/compare.go
- go/bin/score/score.go
- go/goohrli/goohrli.h
- go/pipe/metric.go
- go/resource/pool.go
- go/worker/pool.go
- install_python_metrics.sh
- Added a resource pool that can reuse expensive to create resources.
- Added a metric that uses stdin/stdout of a child process to measure acoustic distances.
- Added a metric that proxies a pool of stdin/stdin-metrics.
- Updated the dependencies in the README.
- Made the resample functions more const.
- Made the zimtohrli audio delta comparison slightly easier to read.
- Added saving functionality to the audio I/O package.
- Added support for the stdin/stdout metric in the compare tool.
- Made the compare tool able to compute multiple metrics in one run.
- Made the compare tool print what metric it's printing.
- Made the worker pool able to fail fast on the first job error.
- Added a fail-fast option to the score tool.
- Made the score tool default to _no_ metrics, and error out if none …
> Added support for metrics hosted by stdin/stdin-communicating persistent processes.

- cpp/zimt/compare.cc
- cpp/zimt/goohrli.cc
- cpp/zimt/pyohrli.cc
- cpp/zimt/pyohrli_test.py
- cpp/zimt/zimtohrli.cc
- cpp/zimt/zimtohrli.h
- cpp/zimt/zimtohrli_test.cc
- go/bin/compare/compare.go
- go/bin/score/score.go
- go/data/study.go
- go/goohrli/goohrli.go
- go/goohrli/goohrli.h
- go/goohrli/goohrli_test.go
- go/progress/bar.go
Made it simpler to compare and optimize.
- Made the size of the unwarp window a field in the Zimtohrli struct.
- Made the Go wrapper bundle all parameters in a single struct that's passed all the way to the C++ layer to avoid having to pipe each parameter individually through several functions.
> Refactored the parameters.

- install_external_metrics.sh
Replaced the coeffs from https://ieeexplore.ieee.org/document/8937179 with coeffs from https://www.audiolabs-erlangen.de/resources/2019-WASPAA-SEBASS/#NewModelParams, which provided slightly better mean performance.
> Replaced the 2f coeffs.

- CMakeLists.txt
- go/bin/score/score.go
- go/data/study.go
Also hopefully fixed the bug where goohrli.a isn't always recreated when needed.
> Made --report and --leaderboard use different precision.

- cpp/zimt/compare.cc
- cpp/zimt/fourier_bank.cc
- cpp/zimt/fourier_bank.h
- cpp/zimt/goohrli.cc
- cpp/zimt/masking.cc
- cpp/zimt/masking.h
- cpp/zimt/masking_test.cc
- cpp/zimt/pyohrli.cc
- cpp/zimt/zimtohrli.cc
- cpp/zimt/zimtohrli.h
- cpp/zimt/zimtohrli_test.cc
|Zimtohrli  |0.101162755033022 |0.563709113431054 |0.773872237318597 |0.691086927997167 | …
> less memory traffic, 3x speedup for tabuli

- cpp/zimt/fourier_bank.cc
- cpp/zimt/zimtohrli.cc
|Zimtohrli  |0.101162746942526 |0.563709113431054 |0.773872237318597 |0.691086968125479 | …
> less memory access by streaming the log10s for dbs

- cpp/zimt/cam.cc
- cpp/zimt/cam.h
- cpp/zimt/fourier_bank.cc
- cpp/zimt/fourier_bank.h
- cpp/zimt/zimtohrli.cc
|Zimtohrli  |0.098637219950560 |0.567187736693103 |0.777010861372363 |0.694493861132456 | …
> more rotators (128->150) improves MSE by a few %

- cpp/zimt/goohrli.cc
- cpp/zimt/pyohrli.cc
- cpp/zimt/pyohrli.py
- cpp/zimt/pyohrli_test.py
- cpp/zimt/zimtohrli.cc
- cpp/zimt/zimtohrli.h
- cpp/zimt/zimtohrli_test.cc
- go/goohrli/goohrli.go
- go/goohrli/goohrli.h
- go/goohrli/goohrli_test.go
StreamingSpectrogram processes audio one 1/perceptual_sample_rate chunk at a time, and therefore needs much less memory allocated for intermediate data.
> Added a streaming spectrogram function

- cpp/zimt/fourier_bank.cc
- cpp/zimt/fourier_bank.h
- cpp/zimt/zimtohrli.cc
|Zimtohrli  |0.097175453861064 |0.581050442393818 |0.776654974298645 |0.696445877155239 | …
> more optimization of heuristics, ~1 % improvement

- cpp/zimt/compare.cc
- cpp/zimt/goohrli.cc
- cpp/zimt/mos.cc
- cpp/zimt/mos.h
- cpp/zimt/mos_test.cc
- cpp/zimt/pyohrli.cc
- cpp/zimt/pyohrli.py
- cpp/zimt/pyohrli_test.py
- cpp/zimt/zimtohrli.h
- go/bin/compare/compare.go
- go/bin/score/score.go
- go/data/study.go
- go/goohrli/goohrli.go
- go/goohrli/goohrli.h
- go/goohrli/goohrli_test.go
- Made the Zimtohrli instance hold a MOSMapper containing the parameters.
- Made all MOS mappings use the current Zimtohrli instance to map to MOS.
- Made the mutable MOS parameters modifiable from Go.
> Made the MOS mapping parameters mutable.

- cpp/zimt/fourier_bank.cc
- cpp/zimt/zimtohrli.cc
not quite sure why this improved so much
changes are too complicated to trace it exactly
much of the improvement was related how I refactored the log10 calculations to be simpler and just log based
|Zimtohrli  |0.090239608814795 |0.534520229950808 |0.772224479921073 |0.707988288758192 |
|CDPAM      |0.153471222942756 |0.441558428344727 …
> ~8 % improvement

- cpp/zimt/fourier_bank.cc
previous tabuli zimtohrli MSE score is 14 % higher than this
after this PR VisQOL will have 47 % higher MSE score than Zimtohrli
|Zimtohrli  |0.078112668596219 |0.607368005163725 |0.828363954766286 |0.727804879676665 |
|PARLAQ     |0.185057687192323 …
> temporal masking

- cpp/zimt/fourier_bank.cc
loudness happens first after this commit
this will help to reduce computation slightly later
|Zimtohrli  |0.078443138275192 |0.602595657239603 |0.824102489042876 |0.727318570435013 |
|PARLAQ     |0.185057687192323 |0.445261140223642 |0.784370761057963 …
> switching loudness and masking

- cpp/zimt/fourier_bank.cc
|Zimtohrli  |0.077647743787295 |0.608127552926780 |0.829014091535645 |0.728679787505096 | …
> ~0.5 % improvement

- cpp/zimt/fourier_bank.cc
- cpp/zimt/nsim.cc
- cpp/zimt/zimtohrli.h
further solidifies Zimtohrli as the best correlating metric
|Zimtohrli  |0.072593165859890 |0.619257037510440 |0.814230081078870 |0.737751119792009 |
|AQUA …
> 7-8 % improvement

- cpp/zimt/fourier_bank.cc
- cpp/zimt/nsim.cc
after something likely went wrong in previous comment
git clumsiness
|Zimtohrli  |0.072654586073989 |0.619257037510440 |0.814288552764735 |0.737622587952872 |
|AQUA …
> quality fix

- cpp/zimt/fourier_bank.cc
- cpp/zimt/fourier_bank.h
- cpp/zimt/zimtohrli.h
|Zimtohrli  |0.076254461155707 |0.589172424723762 |0.806090520228513 |0.731427610098147 | …
> ~5% worse, but faster and simpler

- cpp/zimt/fourier_bank.cc
- cpp/zimt/nsim.cc
- cpp/zimt/zimtohrli.h
taking correct frequency buckets from ISO loudness
reducing structural similarity support area
'''
Score type |MSE               |Min score         |Max score         |Mean score        |
-----------|------------------|------------------|------------------|------------------|
Zimtohrli  |0.074958337059633 |0.609170013051075 |0.804501676659602 |0.732603836275400 |
ViSQOL     |0.115330916105424 |0.520833375452983 |0.801480831107469 |0.675101633981268 |
2f         |0.129541391104905 |0.484687555319526 |0.797475783883375 |0.661870345773127 |
PESQ       |0.147425552045669 |0.342342966279351 |0.841271127756762 |0.647128996775172 |
CDPAM      |0.153471222942756 |0.441558428344727 |0.728779141125759 |0.620699318941738 |
PARLAQ     |0.185057687192323 |0.445261140223642 |0.784370761057963 …
> further simplifications

- cpp/zimt/nsim.cc
adjusting the nsim stabilization parameters
'''
|Zimtohrli  |0.073622255247300 |0.611416768760542 |0.797709696340402 |0.734967593303992 |
|AQUA       |0.223207996944378 …
> minor improvement

- cpp/zimt/fourier_bank.cc
- cpp/zimt/nsim.cc
- cpp/zimt/zimtohrli.h
tuning the existing structures
|Zimtohrli  |0.069100905174817 |0.628756659185876 |0.804728638916679 |0.744043538017276 |
|AQUA       |0.223207996944378 …
> several quality improvements

- python/audio_signal.py
- python/cam.py
- python/cam_test.py
- python/masking.py
- python/zimtohrli.py
- python/zimtohrli_test.py
Changes:
* Make the `Cam` class static from the point of view of jax. To allow jitting, the _hz_freqs array should not be a jax array, because depending on the values of the hyperparameters, the array shape should be different, making it impossible to jit. When attempting to jit the previous version of the code, creating that array under a jit context would fail. -> This requires adjusting the test tolerance from 1e-7 to 1e-5. The equivalent test in c++ uses 1e-2.
* For `Channels` and `Signals` class, mark which fields are data_fields vs. meta_fields (that can be used for JIT cache)
* Remove default arguments that are jnp.array by np.array
* Make the `Masking` class static and remove the `jit` over `non_masked_energy` `self` being the first argument makes it unsuitable for jitting.
* …
> Make Zimtohrli python version easier to jit.

- go/goohrli/goohrli.h
This reverts commit edd6594bc31be96fb78dae7b75fe496e0654d9e7.
Evidently cgo doesn't like the removed 'const' keywords.
> Revert "Fixed lint issues."

- cpp/zimt/compare.cc
Previously, all channels in file b were normalized to the second channel in file a, instead of the correct, corresponding channel. This commit fixes that.
> Fix channel mismatch during normalization

- CMakeLists.txt
- cpp/zimt/compare.cc
- cpp/zimt/fourier_bank.cc
- cpp/zimt/fourier_bank.h
- cpp/zimt/nsim.cc
- cpp/zimt/zimtohrli.cc
- cpp/zimt/zimtohrli.h
- tools/optimizer/random_fork.py
- tools/optimizer/simplex_fork.py
for MOS >= 2.9, in one experiment MSE goes down from 0.111083751524392 to 0.088751221968087
worst improves from 0.412834234172926 to 0.501960846912712
traditionally I have reported full corpus results without MOS filtering, which after this PR are
```
|Zimtohrli  |0.083893276017455 |0.524813698641686 |0.834179239851964 |0.722595805176017 |
|CDPAM …
```
> simplifying, and focusing on MOS >= 2.9

- cpp/zimt/fourier_bank.cc
~2.5 % improvement
```
|Zimtohrli  |0.081764574149153 |0.556914901149026 |0.836478875724214 |0.723880965157041 |
|AQUA       |0.223207996944378 |0.331645933512413 …
```
> restoring basic filter balance from prev version

- CMakeLists.txt
- cpp/zimt/zimtohrli.h
Since its used by other libraries outside the header-only zimtohrli.h it needs to be accessible outside anonymous namespace it seems.
> Moved Span outside the anonymous namespace.

- cpp/zimt/zimtohrli.h
Replace `pow(windowM1, 3.0)` with direct multiplication for better performance.
When raising a value to a small integer power, direct multiplication is more efficient than calling the general `pow` function:
- `pow(x, 3.0)` → `x * x * x`
- Avoids function call overhead
- Compiler can better optimize the multiplication
- More predictable performance
- No loss of precision
- Line 194: Replaced `pow(windowM1, 3.0)` with `(windowM1 * windowM1 * windowM1)`
> Optimize pow(x, 3.0) with multiplication

- CMakeLists.txt
- cmake/visqol.cmake
Directory names containing e.g. digits could cause too little of the path to be stripped.
> Remove variable name prefix more aggressively
